### ISSUE TITLE
Setting port speed

### ISSUE THREAD

**Issue by JTrotta** [crozone/LinuxSerialPort#11]
Hello,
I cannot set port speed. I got an exception. Only 9600 works.
`ad@monitor:~/serial $ sudo stty -F /dev/ttyUSB6 115200
stty: /dev/ttyUSB6: unable to perform all requested operations
`

**Comment by crozone** [comment]
This indicates that the underlying serial driver is incapable of setting the port speed to anything but 9600 baud. What serial device are you using?

**Comment by crozone** [comment]
I'm closing this issue for now as it's not an issue with `LinuxSerialPort` but rather an issue with the underlying tty.
