### ISSUE TITLE
How to change  Baud rate via code

### ISSUE THREAD

**Issue by willhuo** [crozone/LinuxSerialPort#9]
I do not find how to change baud rate via code . And there is no enum setting about baud rate.
Eventhough it could be changed manually.
But I hope to change baud rate via code method.
Thanks.

**Comment by crozone** [comment]
The baud rate can be set with the `LinuxSerialPort.BaudRate` property. The property is an `int`, the supported baud rates will depend on your serial port driver.

For example:

```
// Create the serial port object, using /dev/ttyS0 as the port
//
LinuxSerialPort serialPort = new LinuxSerialPort("/dev/ttyS0");

// Set the baud rate
//
serialPort.BaudRate = 115200;

// Open the port
//
serialPort.Open();
```

The baud rate can also be set after the port has been opened.

I'll document this better in the XML comments, as well as in a code sample in the README.md.
